/// <reference lib="webworker" />

import {
  precacheAndRoute,
  cleanupOutdatedCaches,
  createHandlerBoundToURL,
} from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { clientsClaim } from 'workbox-core';
import { SWSyncQueue } from './lib/sw-sync-queue';
import { get } from 'idb-keyval';

declare const self: ServiceWorkerGlobalScope;

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

// 1. Clean up old caches & Precache assets generated by Vite build
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// 2. Navigation fallback to /index.html for SPA routing
const navigationHandler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(navigationHandler, {
  allowlist: [/^\/$/],
  denylist: [/^\/api\//, /\.[a-z0-9]+$/i],
});
registerRoute(navigationRoute);

// 3. Runtime caching for DiceBear Avatars
registerRoute(
  /^https:\/\/api\.dicebear\.com\/.*/i,
  new CacheFirst({
    cacheName: 'dicebear-avatars',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 Days
      }),
    ],
  })
);

// 4. Handle skipWaiting message from ReloadPrompt UI (useRegisterSW)
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// 5. Service Worker Background Sync Engine
self.addEventListener('sync', (event: any) => {
  if (event.tag === 'sync-chorequest-queue') {
    event.waitUntil(processBackgroundSyncQueue());
  }
});

async function processBackgroundSyncQueue(): Promise<void> {
  const queue = await SWSyncQueue.getQueue();
  if (queue.length === 0 || !SUPABASE_URL || !SUPABASE_ANON_KEY) return;

  console.log(`⚡ SW BackgroundSync processing ${queue.length} queued operations...`);
  const deviceId = (await get<string>('chore-quest-device-id')) || '';
  const remaining = [...queue];

  for (const op of queue) {
    try {
      const headers: Record<string, string> = {
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
        'Content-Type': 'application/json',
      };
      if (deviceId) {
        headers['x-device-id'] = deviceId;
      }

      let res: Response;

      if (op.table === 'rpc') {
        const url = `${SUPABASE_URL}/rest/v1/rpc/${op.payload.function}`;
        res = await fetch(url, {
          method: 'POST',
          headers,
          body: JSON.stringify(op.payload.params || {}),
        });
      } else {
        let url = `${SUPABASE_URL}/rest/v1/${op.table}`;
        let method = 'POST';

        if (op.action === 'insert') {
          method = 'POST';
          headers['Prefer'] = 'return=minimal';
        } else if (op.action === 'update') {
          method = 'PATCH';
          if (op.match) {
            url += `?${op.match.column}=eq.${encodeURIComponent(op.match.value)}`;
          }
        } else if (op.action === 'delete') {
          method = 'DELETE';
          if (op.match) {
            url += `?${op.match.column}=eq.${encodeURIComponent(op.match.value)}`;
          }
        }

        res = await fetch(url, {
          method,
          headers,
          body: op.action !== 'delete' ? JSON.stringify(op.payload) : undefined,
        });
      }

      if (!res.ok) {
        console.error(`SW BackgroundSync operation ${op.id} failed with HTTP ${res.status}`);
        break; // Stop execution to maintain operation ordering
      }

      const idx = remaining.findIndex((item) => item.id === op.id);
      if (idx !== -1) remaining.splice(idx, 1);
    } catch (err) {
      console.error(`SW BackgroundSync network error processing ${op.id}:`, err);
      break;
    }
  }

  await SWSyncQueue.setQueue(remaining);
}

// 6. Remote Web Push Notification Handler
self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const payload = event.data.json();
    const title = payload.title || 'ChoreQuest';
    const options: NotificationOptions = {
      body: payload.body || '',
      icon: payload.icon || '/pwa-192x192.png',
      badge: payload.badge || '/favicon-196.png',
      tag: payload.tag || `push-${Date.now()}`,
      data: {
        url: payload.url || '/',
      },
    };

    event.waitUntil(self.registration.showNotification(title, options));
  } catch (err) {
    console.error('Failed to process incoming Web Push payload:', err);
  }
});

// 7. Notification Click Handler (Focus/Open Tab)
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const targetUrl = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (const client of windowClients) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          if ('navigate' in client) {
            client.navigate(targetUrl);
          }
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl);
      }
    })
  );
});

clientsClaim();
